name: BungeePortals
version: unknown
description: Create portals of any shape or size with WorldEdit, for BungeeCord. Edited for DyrtCraft Network by TheMolkaPL (themolkapl@gmail.com)
authors: [YoFuzzy3, TheMolkaPL]
main: com.fuzzoland.BungeePortals.BungeePortals
dev-url: http://www.spigotmc.org/resources/bungeeportals.19/
softdepend: [WorldEdit, DyrtCraftXP]

commands:
    BPortals:
        description: Do cool stuff.
permissions:
    BungeePortals.command.BPortals:
        description: Allowed to access the command /BPortals.
        default: op
    BungeePortals.portal.*:
        description: Access to all portals.
        default: true